# Generated by Django 6.0.3 on 2026-03-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_user_is_identity_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('phones', 'Phones'), ('laptops', 'Laptops'), ('accessories', 'Accessories'), ('tablets', 'Tablets'), ('audio', 'Audio'), ('gaming', 'Gaming'), ('home_office', 'Home Office'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='used_good', max_length=32),
        ),
        migrations.AddField(
            model_name='listing',
            name='defects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='gallery_image_urls',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
