# Generated by Django 6.0.3 on 2026-03-24 20:30

from django.db import migrations, models


def migrate_controlled_transaction_data(apps, schema_editor):
    Offer = apps.get_model("accounts", "Offer")
    Transaction = apps.get_model("accounts", "Transaction")

    Offer.objects.filter(status="declined").update(status="rejected")

    status_map = {
        "awaiting_payment": "pending_payment",
        "offer_sent": "cancelled",
        "offer_accepted": "pending_payment",
        "payment_completed": "awaiting_meetup",
    }
    for old_status, new_status in status_map.items():
        Transaction.objects.filter(status=old_status).update(status=new_status)

    Transaction.objects.filter(status="completed").update(is_released=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_listing_category_listing_condition_listing_defects_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="price",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(migrate_controlled_transaction_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("locked", "Locked"),
                    ("sold", "Sold"),
                    ("inactive", "Inactive"),
                    ("draft", "Draft"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Awaiting response"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending payment"),
                    ("payment_in_progress", "Payment in progress"),
                    ("payment_confirmed", "Payment confirmed"),
                    ("locked", "Locked"),
                    ("awaiting_meetup", "Awaiting meetup"),
                    ("awaiting_confirmation", "Awaiting confirmation"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("disputed", "Disputed"),
                ],
                default="pending_payment",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(payment_reference__isnull=False) & ~models.Q(payment_reference=""),
                fields=("payment_reference",),
                name="accounts_transaction_unique_payment_reference",
            ),
        ),
    ]
