# Generated by Django 6.0.3 on 2026-03-24 20:48

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_controlled_transaction_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='primary_image',
            field=models.FileField(blank=True, upload_to=accounts.models.listing_primary_image_upload_to),
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=16)),
                ('file', models.FileField(upload_to=accounts.models.listing_media_upload_to)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='accounts.listing')),
            ],
            options={
                'ordering': ['position', 'created_at', 'pk'],
            },
        ),
    ]
