# Generated by Django 6.0.3 on 2026-03-24 21:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_listing_primary_image_listingmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='user',
            name='cac_certificate',
            field=models.FileField(blank=True, upload_to=accounts.models.user_compliance_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='social_handle',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
