# Generated by Django 6.0.3 on 2026-03-24 21:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_account_type_user_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_document',
            field=models.FileField(blank=True, upload_to=accounts.models.user_identity_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document_type',
            field=models.CharField(blank=True, choices=[('nin', 'NIN'), ('national_id', 'National ID'), ('voters_card', "Voter's Card"), ('drivers_license', "Driver's License")], max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
