"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b&8^jb+2grgk$41qm*3@!-efch+!6gqi0=7ly6eo8_4a$zftid'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = [
    'accounts.auth_backends.PhoneOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'auth_login'
LOGIN_REDIRECT_URL = 'dashboard_home'
LOGOUT_REDIRECT_URL = 'auth_login'

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_SESSION_TOKEN = os.getenv('AWS_SESSION_TOKEN', '')
AWS_REGION = os.getenv('AWS_REGION', 'us-east-1')
AWS_SES_ACCESS_KEY_ID = os.getenv('AWS_SES_ACCESS_KEY_ID', AWS_ACCESS_KEY_ID)
AWS_SES_SECRET_ACCESS_KEY = os.getenv('AWS_SES_SECRET_ACCESS_KEY', AWS_SECRET_ACCESS_KEY)
AWS_SES_SESSION_TOKEN = os.getenv('AWS_SES_SESSION_TOKEN', AWS_SESSION_TOKEN)
AWS_SES_REGION = os.getenv('AWS_SES_REGION', AWS_REGION)
AWS_SES_FROM_EMAIL = os.getenv('AWS_SES_FROM_EMAIL', '')
AWS_SES_REPLY_TO_EMAIL = os.getenv('AWS_SES_REPLY_TO_EMAIL', '')
AWS_SES_CONFIGURATION_SET = os.getenv('AWS_SES_CONFIGURATION_SET', '')
AWS_SES_ENDPOINT_URL = os.getenv('AWS_SES_ENDPOINT_URL', '')

TERMII_API_KEY = os.getenv('TERMII_API_KEY', '')
TERMII_SENDER_ID = os.getenv('TERMII_SENDER_ID', '')
TERMII_BASE_URL = os.getenv('TERMII_BASE_URL', 'https://api.ng.termii.com/api')

PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_BASE_URL = os.getenv('PAYSTACK_BASE_URL', 'https://api.paystack.co')
PAYSTACK_CALLBACK_URL = os.getenv('PAYSTACK_CALLBACK_URL', '')
PAYSTACK_CURRENCY = os.getenv('PAYSTACK_CURRENCY', 'NGN')
PAYSTACK_CHANNELS = [
    channel.strip()
    for channel in os.getenv('PAYSTACK_CHANNELS', '').split(',')
    if channel.strip()
]

DECLUTRO_PAYMENT_WINDOW_HOURS = int(os.getenv('DECLUTRO_PAYMENT_WINDOW_HOURS', '1'))
DECLUTRO_ACCEPTED_OFFER_PAYMENT_WINDOW_HOURS = int(
    os.getenv('DECLUTRO_ACCEPTED_OFFER_PAYMENT_WINDOW_HOURS', '2')
)
DECLUTRO_OFFER_EXPIRATION_HOURS = int(os.getenv('DECLUTRO_OFFER_EXPIRATION_HOURS', '24'))
DECLUTRO_AUTO_RELEASE_DAYS = int(os.getenv('DECLUTRO_AUTO_RELEASE_DAYS', '0'))
